package Modelo;
// Generated 11-23-2014 10:06:42 AM by Hibernate Tools 3.6.0



/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private short idrol;
     private String nombre;
     private String descripcion;
     private byte nivel;

    public Rol() {
    }

    public Rol(short idrol, String nombre, String descripcion, byte nivel) {
       this.idrol = idrol;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.nivel = nivel;
    }
   
    public short getIdrol() {
        return this.idrol;
    }
    
    public void setIdrol(short idrol) {
        this.idrol = idrol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public byte getNivel() {
        return this.nivel;
    }
    
    public void setNivel(byte nivel) {
        this.nivel = nivel;
    }




}


